### PR TITLE
Refactor CMakeLists.txt files

### PR DESCRIPTION
**Pull request by jmossberg**
Hi!

Great project! :)

I have created a proposal on how to refactor CMakeLists.txt files in order to follow how I understand so called "Modern CMake" guidelines:
* Set dependencies and properties on targets directly using e.g. target_link_libraries
* Avoid setting global settings through e.g. include_directories

I have done the following changes:
* Set project name and minimum CMake version in the top CMakelists.txt file only
* Add subdirectory lib using add_subdirectoy instead of via include_directories
* Add a CMakeLists.txt file to lib folder
* Use command target_link_libraries in the tests folder to link tests with 
libraries defined in the code and lib folders
* Set C++17 standard on the defined targets instead of as a general variable

Best regards,
Jacob

### CODE REVIEW

**Comment by claremacrae** [comment]
Hi Jacob, thank you for this - I’ll look at it fully tomorrow.

**Comment by claremacrae** [comment]
Hi Jacob,

Thanks very much for this - it's a great improvement to our cmake files...

Just one question - there's now some repetition of the target names in the sub-directories, which can be a bit error-prone.  For example, this use of `StarterProject.tests` in the `tests` sub-directory:

```cmake
add_executable(StarterProject.tests ${SOURCE_FILES} )

target_link_libraries(StarterProject.tests StarterProject.code StarterProject.lib)

set(TARGET StarterProject.tests PROPERTY CXX_STANDARD 17)

add_test(NAME StarterProject.tests COMMAND StarterProject.tests)
```

In the `code` sub-dir, we used to use `${PROJECT_NAME}` - and we see you've removed that now. Just curious - what's the reason for removing that in sub-dirs, and can you suggest any way to remove that repetition now?

Thanks again for the help!

Clare and Llewellyn

**Comment by jmossberg** [comment]
Hi Clare and Llewellyn!

I think you got a valid point. Maybe there is a better way that avoids the repetition. I am still trying to figure out how to handle CMake.

My understanding of the project command is that it is usually only used in the top CMakeLists.txt of a project. Not in every sub-folder. That is why I removed it.

I tried with the following variant of code/CMakeLists.txt and it seems to work and would resemble how you got rid of the repetition before when you were able to use the ${PROJECT_NAME} variable.

```
set(CODE_LIB_NAME StarterProject.code)
add_library(${CODE_LIB_NAME} INTERFACE)
target_include_directories(${CODE_LIB_NAME}
        INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
set(TARGET ${CODE_LIB_NAME} PROPERTY CXX_STANDARD 17)
```
What do you think?

My current knowledge of how to do CMake was inspired by a talk a listened to at MeetingC++ 2018:

- https://jacobmossberg.se/posts/2019/01/23/meeting-cpp-2018-travel-report.html#more-modern-cmake---working-with-cmake-312-and-later-deniz-bahadir
- https://github.com/Bagira80/More-Modern-CMake

//Jacob

**Comment by claremacrae** [comment]
Hi Jacob

Thanks for the reply.

FYI, we ended up temporarily backing out these changes as it turned out that it broke the CI build... We will pick this up again - we just didn't have time to fix it today...

Clare

**Pull request merged**
